services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ammdevpass"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "3333:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "sqlserver"

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "8888:8080"
    volumes:
      - "../wiremock:/home/wiremock"
    command: ["--verbose"]

volumes:
  sqlserver_data: